"""Add and enhance constraints

Revision ID: c6fb480ab86a
Revises: c6c4b1a32cb1
Create Date: 2024-11-19 18:16:27.196582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6fb480ab86a'
down_revision = 'c6c4b1a32cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')
    op.drop_constraint('books_library_id_fkey', 'books', type_='foreignkey')
    op.drop_constraint('books_borrowed_by_fkey', 'books', type_='foreignkey')
    op.create_foreign_key('books_borrowed_by_users_id_fk', 'books', 'users', ['borrowed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('books_author_id_authors_id_fk', 'books', 'authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('books_library_id_libraries_id_fk', 'books', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('library_users_library_id_fkey', 'library_users', type_='foreignkey')
    op.drop_constraint('library_users_user_id_fkey', 'library_users', type_='foreignkey')
    op.create_foreign_key('library_users_user_id_users_id_fk', 'library_users', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('library_users_library_id_libraries_id_fk', 'library_users', 'libraries', ['library_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('library_users_library_id_libraries_id_fk', 'library_users', type_='foreignkey')
    op.drop_constraint('library_users_user_id_users_id_fk', 'library_users', type_='foreignkey')
    op.create_foreign_key('library_users_user_id_fkey', 'library_users', 'users', ['user_id'], ['id'])
    op.create_foreign_key('library_users_library_id_fkey', 'library_users', 'libraries', ['library_id'], ['id'])
    op.drop_constraint('books_library_id_libraries_id_fk', 'books', type_='foreignkey')
    op.drop_constraint('books_author_id_authors_id_fk', 'books', type_='foreignkey')
    op.drop_constraint('books_borrowed_by_users_id_fk', 'books', type_='foreignkey')
    op.create_foreign_key('books_borrowed_by_fkey', 'books', 'users', ['borrowed_by'], ['id'])
    op.create_foreign_key('books_library_id_fkey', 'books', 'libraries', ['library_id'], ['id'])
    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###
