---
# Note: replacement needed
name: Build and Deploy
on:  # yamllint disable-line rule:truthy
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
    branches:
      - master
  release:
    types: [created]
  pull_request:
    branches:
      - master

jobs:
  build_and_run_test:
    name: build_and_run_test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: read
      actions: write
      contents: read
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
